services:
  postgres:
    image: postgres:16.7
    container_name: notification_bot_db
    env_file:
      - ./bot/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_data:
