"""Created notifications table

Revision ID: a50ee7db906d
Revises:
Create Date: 2025-10-26 20:55:59.662871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50ee7db906d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("notif_time", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum("ONE_TIME", "DAILY", name="notificationtypeenum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_telegram_id"),
        "notifications",
        ["telegram_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_telegram_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
