"""Added field notification_type to notifications table

Revision ID: 0ca980cfc330
Revises: 1145a9fe487a
Create Date: 2025-10-25 23:28:09.483855

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ca980cfc330"
down_revision: str | Sequence[str] | None = "1145a9fe487a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("notification_type", sa.String(length=10), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "notification_type")
    # ### end Alembic commands ###
